apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-rabbitmq
spec:
  selector:
    matchLabels:
      app: chat-rabbitmq
  template:
    metadata:
      labels:
        app: chat-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-rabbitmq
spec:
  selector:
    app: chat-rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
